[RNI_setting]
r = 4
n = 3
i = 8

[QP]
QP = 3

[I_Frame]
period = 4

[frame]
frame = 10

[resolution]
w = 352
h = 288

[nRefFrames]
nRefFrames = 1

[VBSEnable]
VBSEnable = True
j = 3

[FMEEnable]
FMEEnable = False

[FastME]
FastME = False