[RNI_setting]
r = 4
n = 0
i = 8

[QP]
QP = 0

[I_Frame]
period = 10

[frame]
frame = 10

[resolution]
w = 352
h = 288

[nRefFrames]
nRefFrames = 4

[VBSEnable]
VBSEnable = True
j = 3
lambda_coefficient = 1.2

[FMEEnable]
FMEEnable = False

[FastME]
FastME = True