[RNI_setting]
r = 4
n = 3
i = 16

[QP]
QP = 1

[I_Frame]
period = 8

[frame]
frame = 10

[resolution]
w = 352
h = 288

[nRefFrames]
nRefFrames = 4

[VBSEnable]
VBSEnable = True
j = 4
lambda_coefficient = 2.5

[FMEEnable]
FMEEnable = False

[FastME]
FastME = False