[RNI_setting]
r = 16
n = 3
i = 16

[QP]
QP = 5

[I_Frame]
period = 10

[frame]
frame = 21

[resolution]
w = 352
h = 288

[nRefFrames]
nRefFrames = 1

[VBSEnable]
VBSEnable = True
j = 4
lambda_coefficient = 2.5

[FMEEnable]
FMEEnable = True

[FastME]
FastME = True

[RCFlag]
RCFlag = 0
targetBR = 2,737,152
FPS = 30
intraLine = 1.5

[ParallelMode]
ParallelMode = 1