# [Default_test_r8i4]
# FMEEnable = False
# FastME = False
# nRefFrames = 1
# VBSEnable = False
# r = 8
# i = 4

# [Default_test_r4i8]
# FMEEnable = False
# FastME = False
# nRefFrames = 1
# VBSEnable = False
# r = 4
# i = 8

# [Default_test_r1i8]
# FMEEnable = False
# FastME = False
# nRefFrames = 1
# VBSEnable = False
# r = 1
# i = 8

# [Default_test_r8i8]
# FMEEnable = False
# FastME = False
# nRefFrames = 1
# VBSEnable = False
# r = 8
# i = 8

[Default_test]
FMEEnable = False
FastME = False
nRefFrames = 1
VBSEnable = False

[MRF_test]
FMEEnable = False
FastME = False
nRefFrames = 4
VBSEnable = False

[VBSEnable_test]
FMEEnable = False
FastME = False
nRefFrames = 1
VBSEnable = True
j = 4
lambda_coefficient = 1.2

[FractionME_test]
FMEEnable = True
FastME = False
nRefFrames = 1
VBSEnable = False

[FastMME_test]
FMEEnable = False
FastME = True
nRefFrames = 1
VBSEnable = False

[AllEnable_test]
FMEEnable = True
FastME = True
nRefFrames = 4
VBSEnable = True
j = 4
lambda_coefficient = 1.2
